# Generated by Django 5.1 on 2024-09-02 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('funcionarios', models.ManyToManyField(to='precificacao.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='CalculoPrecificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_servico_prestado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda_com_impostos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precificacao.projeto')),
            ],
        ),
    ]
